/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.babin.langlearn.ui2;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import ru.babin.langlearn.core.FileProcessor;
import ru.babin.langlearn.core.Mediator;
import ru.babin.langlearn.util.ConfGlobal;

/**
 *
 * @author alexander
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    
    JFileChooser fileChooser = new JFileChooser();
    FileProcessor fileProcessor = new FileProcessor();
    final Mediator mediator = new Mediator();
    
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        fileChooser.setCurrentDirectory(new File(ConfGlobal.getAppDir()));
        
        mediator.setLstUnknownWords(lstUnknownWords);
        mediator.setLblUnknownWordsCount(lblUnknownWordsCount);
        mediator.setLblVocabularyInfo(lblVocabularyInfo);
        mediator.init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMiddle = new javax.swing.JPanel();
        scrlUnknownWords = new javax.swing.JScrollPane();
        lstUnknownWords = new javax.swing.JList<>();
        lblUnknownWords = new javax.swing.JLabel();
        lblUnknownWordsCount = new javax.swing.JLabel();
        lblOpenFile = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        lblVocabulary = new javax.swing.JLabel();
        lblVocabularyInfo = new javax.swing.JLabel();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuItemOpenFile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foreign languages learning :)");
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(400, 2000));
        setMinimumSize(new java.awt.Dimension(500, 300));

        pnlMiddle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        scrlUnknownWords.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lstUnknownWords.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lstUnknownWords.setToolTipText("Unknown words list");
        lstUnknownWords.setMaximumSize(new java.awt.Dimension(36, 0));
        scrlUnknownWords.setViewportView(lstUnknownWords);

        lblUnknownWords.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUnknownWords.setText("Unknown words");

        lblUnknownWordsCount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUnknownWordsCount.setText("0");

        lblOpenFile.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOpenFile.setForeground(new java.awt.Color(0, 0, 0));
        lblOpenFile.setText("...");

        javax.swing.GroupLayout pnlMiddleLayout = new javax.swing.GroupLayout(pnlMiddle);
        pnlMiddle.setLayout(pnlMiddleLayout);
        pnlMiddleLayout.setHorizontalGroup(
            pnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMiddleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOpenFile, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addGroup(pnlMiddleLayout.createSequentialGroup()
                        .addGroup(pnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrlUnknownWords, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMiddleLayout.createSequentialGroup()
                                .addComponent(lblUnknownWords)
                                .addGap(28, 28, 28)
                                .addComponent(lblUnknownWordsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMiddleLayout.setVerticalGroup(
            pnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMiddleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOpenFile)
                .addGap(13, 13, 13)
                .addGroup(pnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnknownWords)
                    .addComponent(lblUnknownWordsCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlUnknownWords, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlBottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblVocabulary.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblVocabulary.setText("Vocabulary");

        lblVocabularyInfo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblVocabularyInfo.setText("...");

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVocabulary)
                .addGap(18, 18, 18)
                .addComponent(lblVocabularyInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVocabulary)
                    .addComponent(lblVocabularyInfo))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        mnuFile.setText("File");
        mnuFile.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        mnuItemOpenFile.setText("Open file ...");
        mnuItemOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemOpenFileActionPerformed(evt);
            }
        });
        mnuFile.add(mnuItemOpenFile);

        mnuBar.add(mnuFile);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemOpenFileActionPerformed
        
        String filename= "";
        String dir = "";
        
        // Demonstrate "Open" dialog:
        int res = fileChooser.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
          filename = fileChooser.getSelectedFile().getName();
          dir = fileChooser.getCurrentDirectory().toString();
        }
                        
        if(!filename.isEmpty()){
            processSelectedFile(dir + File.separator + filename);
        }
        
    }//GEN-LAST:event_mnuItemOpenFileActionPerformed
    
    private void processSelectedFile(String filePath) {
        try {
            List<String> words = fileProcessor.process(filePath);
            mediator.eventNewLoadedWords(words);
            lblOpenFile.setText("Opened file: " + filePath);
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "filename: " + filePath + "  ;  Error processing !!!");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblOpenFile;
    private javax.swing.JLabel lblUnknownWords;
    private javax.swing.JLabel lblUnknownWordsCount;
    private javax.swing.JLabel lblVocabulary;
    private javax.swing.JLabel lblVocabularyInfo;
    private javax.swing.JList<String> lstUnknownWords;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuItemOpenFile;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlMiddle;
    private javax.swing.JScrollPane scrlUnknownWords;
    // End of variables declaration//GEN-END:variables
}
